git:
  depth: false # fetch all branches
services:
  - docker
matrix:
  include:
    - env: RESTYLER=astyle
    - env: RESTYLER=autopep8
    - env: RESTYLER=black
    - env: RESTYLER=brittany
    - env: RESTYLER=clang-format
    - env: RESTYLER=dhall-format
    - env: RESTYLER=dfmt
    - env: RESTYLER=dotnet-format
    - env: RESTYLER=elm-format
    - env: RESTYLER=fantomas
    - env: RESTYLER=gn
    - env: RESTYLER=google-java-format
    - env: RESTYLER=hindent
    - env: RESTYLER=hlint
    - env: RESTYLER=isort
    - env: RESTYLER=jdt
    - env: RESTYLER=ormolu
    - env: RESTYLER=pg_format
    - env: RESTYLER=php-cs-fixer
    - env: RESTYLER=prettier
    - env: RESTYLER=prettier-json
    - env: RESTYLER=prettier-markdown
    - env: RESTYLER=prettier-ruby
    - env: RESTYLER=prettier-yaml
    - env: RESTYLER=reorder-python-imports
    - env: RESTYLER=rubocop
    - env: RESTYLER=rustfmt
    - env: RESTYLER=shellharden
    - env: RESTYLER=shfmt
    - env: RESTYLER=stylish-haskell
    - env: RESTYLER=terraform
    - env: RESTYLER=whitespace
    - env: RESTYLER=yapf
install:
  - docker pull hadolint/hadolint
  - docker pull restyled/restylers:v1
script: ./build/ci
