git:
  depth: false  # fetch all branches
language: python
services: [docker]
matrix:
  include:
    - env: TARGET=astyle/Dockerfile.tested
    - env: TARGET=autopep8/Dockerfile.tested
    - env: TARGET=black/Dockerfile.tested
    - env: TARGET=brittany/Dockerfile.tested
    - env: TARGET=clang-format/Dockerfile.tested
    - env: TARGET=dfmt/Dockerfile.tested
    - env: TARGET=elm-format/Dockerfile.tested
    - env: TARGET=google-java-format/Dockerfile.tested
    - env: TARGET=hindent/Dockerfile.tested
    - env: TARGET=hlint/Dockerfile.tested
    - env: TARGET=jdt/Dockerfile.tested
    - env: TARGET=ormolu/Dockerfile.tested
    - env: TARGET=pg_format/Dockerfile.tested
    - env: TARGET=php-cs-fixer/Dockerfile.tested
    - env: TARGET=prettier/Dockerfile.tested
    - env: TARGET=prettier-markdown/Dockerfile.tested
    - env: TARGET=prettier-ruby/Dockerfile.tested
    - env: TARGET=prettier-yaml/Dockerfile.tested
    - env: TARGET=reorder-python-imports/Dockerfile.tested
    - env: TARGET=rubocop/Dockerfile.tested
    - env: TARGET=rustfmt/Dockerfile.tested
    - env: TARGET=shellharden/Dockerfile.tested
    - env: TARGET=shfmt/Dockerfile.tested
    - env: TARGET=stylish-haskell/Dockerfile.tested
    - env: TARGET=terraform/Dockerfile.tested
    - env: TARGET=yapf/Dockerfile.tested
    - env: TARGET=generate-travis
install: pip install cram
script: build/make-if-target-changed "$TARGET"
