git:
  depth: false # fetch all branches
language: ruby
rvm:
  - 2.6
services: [docker]
matrix:
  include:
    - env: RESTYLER=astyle
    - env: RESTYLER=autopep8
    - env: RESTYLER=black
    - env: RESTYLER=brittany
    - env: RESTYLER=clang-format
    - env: RESTYLER=dfmt
    - env: RESTYLER=dotnet-format
    - env: RESTYLER=elm-format
    - env: RESTYLER=fantomas
    - env: RESTYLER=gn
    - env: RESTYLER=google-java-format
    - env: RESTYLER=hindent
    - env: RESTYLER=hlint
    - env: RESTYLER=isort
    - env: RESTYLER=jdt
    - env: RESTYLER=ormolu
    - env: RESTYLER=pg_format
    - env: RESTYLER=php-cs-fixer
    - env: RESTYLER=prettier
    - env: RESTYLER=prettier-json
    - env: RESTYLER=prettier-markdown
    - env: RESTYLER=prettier-ruby
    - env: RESTYLER=prettier-yaml
    - env: RESTYLER=reorder-python-imports
    - env: RESTYLER=rubocop
    - env: RESTYLER=rustfmt
    - env: RESTYLER=shellharden
    - env: RESTYLER=shfmt
    - env: RESTYLER=stylish-haskell
    - env: RESTYLER=terraform
    - env: RESTYLER=whitespace
    - env: RESTYLER=yapf
install: gem install rspec
script: |
  # failure means we're on the "push" job. we'll just diff against parent
  mb=$(git merge-base master HEAD 2>/dev/null || echo "HEAD^")

  if ! git diff --name-only "$mb" | grep -q "^${RESTYLER}/"; then
    echo "$RESTYLER unchanged, skipping."
    exit 0
  fi

  parent=$(./build/restyler-meta overrides "$RESTYLER")

  if [ -n "$parent" ]; then
    make "$parent"/Dockerfile.built "$RESTYLER".tested
  else
    make "$RESTYLER"/Dockerfile.tested
  fi
