name: Release to dev channel manifest

on:
  push:
    branches: master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: |
            docker-layer-caching-${{ github.workflow }}-${{ matrix.restyler }}-{hash}
          restore-keys: |
            docker-layer-caching-${{ github.workflow }}-${{ matrix.restyler }}-

      - name: Setup
        run: |
          docker pull hadolint/hadolint
          docker pull restyled/sdk:main

      - name: Login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.dockerhub_username }}
          DOCKERHUB_PASSWORD: ${{ secrets.dockerhub_password }}
        run: docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

      - name: Release
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          DOCKERHUB_USERNAME: ${{ secrets.dockerhub_username }}
          DOCKERHUB_PASSWORD: ${{ secrets.dockerhub_password }}
        run: |
          docker run --rm \
            --env AWS_ACCESS_KEY_ID \
            --env AWS_SECRET_ACCESS_KEY \
            --env AWS_DEFAULT_REGION=us-east-1 \
            --env "REALPWD=$PWD" \
            --volume "$PWD":/code \
            --volume /tmp:/tmp \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            --volume "$HOME"/.docker/config.json:/root/.docker/config.json:ro \
            --entrypoint sh \
            restyled/sdk:main -c '
              restyled restylers release --write /tmp/restylers.yaml ./*/info.yaml
              restyled promote --no-test --file /tmp/restylers.yaml dev
            '

  status:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - run: echo "Job to act as our overall required PR Status"
