name: Release to dev channel

on:
  push:
    branches: main

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        restyler:
          - astyle
          - autopep8
          - black
          - brittany
          - clang-format
          - dfmt
          - dhall-format
          - dotnet-format
          - elm-format
          - fantomas
          - gn
          - gofmt
          - google-java-format
          - hindent
          - hlint
          - isort
          - jdt
          - jq
          - ormolu
          - pg_format
          - php-cs-fixer
          - prettier
          - prettier-json
          - prettier-markdown
          - prettier-ruby
          - prettier-yaml
          - reorder-python-imports
          - rubocop
          - rustfmt
          - shellharden
          - shfmt
          - stylish-haskell
          - terraform
          - whitespace
          - yapf

    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: docker-layer-caching-${{ matrix.restyler }}-{hash}
          restore-keys: docker-layer-caching-${{ matrix.restyler }}-

      - name: Setup
        run: |
          docker pull hadolint/hadolint
          docker pull restyled/sdk:main

      - name: Login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.dockerhub_username }}
          DOCKERHUB_PASSWORD: ${{ secrets.dockerhub_password }}
        run: |
          echo "$DOCKERHUB_PASSWORD" |
            docker login --username "$DOCKERHUB_USERNAME" --password-stdin

      - name: Release
        run: |
          docker run --rm \
            --env "REALPWD=$PWD" \
            --volume "$PWD":/code \
            --volume /tmp:/tmp \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            --volume "$HOME"/.docker/config.json:/root/.docker/config.json:ro \
            restyled/sdk:main restylers \
              --push --write /tmp/restyler.yaml ${{ matrix.restyler }}/info.yaml

      - name: Upload as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.restyler }}
          path: /tmp/restyler.yaml

  manifest:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2

      - name: Setup
        run: |
          docker pull restyled/sdk:main

      - name: Promote
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          cat **/*.yaml | docker run --rm --interactive \
            --env AWS_ACCESS_KEY_ID \
            --env AWS_SECRET_ACCESS_KEY \
            --env AWS_DEFAULT_REGION \
            restyled/sdk:main promote --no-test --file - dev

      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag-version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag-version.outputs.new_tag }}
          release_name: Release ${{ steps.tag-version.outputs.new_tag }}
          body: ${{ steps.tag-version.outputs.changelog }}

      - name: Promote tag
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          docker run --rm \
            --env AWS_ACCESS_KEY_ID \
            --env AWS_SECRET_ACCESS_KEY \
            --env AWS_DEFAULT_REGION \
            restyled/sdk:main promote --no-test dev ${{ steps.tag-version.outputs.new_tag }}

  status:
    runs-on: ubuntu-latest
    needs: manifest
    steps:
      - run: echo "Job to act as our overall required PR Status"
